Repository tl-its-umich-edu/canvas-course-manager-next, pull requests merged in 2021-12, with the labels that each got.

#251 Improve session (#171)
  ccm_web/server/localTypes/express-session/index.d.ts
  ccm_web/server/src/api/api.controller.ts
  ccm_web/server/src/auth/auth.controller.ts
  ccm_web/server/src/auth/session.guard.ts
  ccm_web/server/src/canvas/canvas.controller.ts
  ccm_web/server/src/lti/lti.service.ts
  ccm_web/server/src/main.ts
Labels: enhancement, back end, API, oauth

#273 Modify layout, file name, and language in documentation section in `README.md`
  README.md
Labels: documentation, enhancement

#267 Add `yup` for basic string validation, implement field validation in `InlineTextEdit` (#244, #276)
  ccm_web/client/src/components/BulkSectionCreateValidators.ts
  ccm_web/client/src/components/InlineTextEdit.tsx
  ccm_web/client/src/pages/BulkSectionCreate.tsx
  ccm_web/client/src/pages/Home.tsx
  ccm_web/client/src/utils/ThirdPartyGradebookProcessor.tsx
  ccm_web/client/src/utils/canvasSectionNameValidator.ts
  ccm_web/client/src/utils/validation.ts
  ccm_web/package-lock.json
  ccm_web/package.json
Labels: enhancement, front end, usability, dependencies

#268 #266 renaming UM to U-M text
  ccm_web/client/src/models/feature.ts
  docs/_data/navigation.yml
  docs/add-um-users.html
  docs/gradebook-canvas.html
  docs/gradebook-thirdparty.html
Labels: front end

#262 issue-142 prevent user with wrong roles to access CCM tool
  ccm_web/server/src/canvas/canvas.interfaces.ts
  ccm_web/server/src/lti/lti.service.ts
Labels: enhancement, back end

#282 #265 #75 creating theme and fixing the error icon color
  ccm_web/client/src/components/CSVFileName.tsx
  ccm_web/client/src/components/ConfirmDialog.tsx
  ccm_web/client/src/components/ErrorAlert.tsx
  ccm_web/client/src/components/FileUpload.tsx
  ccm_web/client/src/components/SuccessCard.tsx
  ccm_web/client/src/components/WarningAlert.tsx
  ccm_web/client/src/index.tsx
  ccm_web/client/src/pages/GradebookCanvas.tsx
  ccm_web/client/src/theme.ts
Labels: 🐛 bug, enhancement, front end, usability
