Repository tl-its-umich-edu/canvas-course-manager-next, pull requests merged in 2021-05, with the labels that each got.

#72 Fix a few misc. `ltijs` typing issues (#71)
  ccm_web/server/localTypes/ltijs/index.d.ts
Labels: back end, bug

#65 Canvas Gradebook
  ccm_web/client/src/App.tsx
  ccm_web/client/src/components/ConfirmationTable.tsx
  ccm_web/client/src/components/FileUpload.tsx
  ccm_web/client/src/components/TablePagination.tsx
  ccm_web/client/src/components/ValidationErrorTable.tsx
  ccm_web/client/src/models/FeatureUIData.tsx
  ccm_web/client/src/models/feature.ts
  ccm_web/client/src/pages/GradebookCanvas.tsx
  ccm_web/package-lock.json
  ccm_web/package.json
Labels: enhancement, feature, front end

#68 Re-structure and improve backend using NestJS (#67)
  README.md
  ccm_web/.eslintrc.js
  ccm_web/Dockerfile
  ccm_web/package-lock.json
  ccm_web/package.json
  ccm_web/server/apiRouter.ts
  ccm_web/server/app.ts
  ccm_web/server/appHandler.ts
  ccm_web/server/nest-cli.json
  ccm_web/server/src/api/api.controller.spec.ts
  ccm_web/server/src/api/api.controller.ts
  ccm_web/server/src/api/api.interfaces.ts
  ccm_web/server/src/api/api.module.ts
  ccm_web/server/src/api/api.service.ts
  ccm_web/server/src/app.module.ts
  ccm_web/server/src/config.ts
  ccm_web/server/src/logger.ts
  ccm_web/server/src/lti/lti.middleware.ts
  ccm_web/server/src/lti/lti.module.ts
  ccm_web/server/src/lti/lti.service.ts
  ccm_web/server/src/main.ts
  ccm_web/server/test/app.e2e-spec.ts
  ccm_web/server/test/jest-e2e.json
  ccm_web/tsconfig.build.json
  ccm_web/tsconfig.json
  ccm_web/webpack/webpack.common.ts
  config/lti_dev_key_sample.json
Labels: API, back end, config change, enhancement

#83 Add OpenAPI/Swagger (#82)
  README.md
  ccm_web/client/src/App.tsx
  ccm_web/package-lock.json
  ccm_web/package.json
  ccm_web/server/src/api/api.controller.ts
  ccm_web/server/src/main.ts
Labels: API, back end, enhancement

#80 NestJS ORM DB integration
  README.md
  ccm_web/Dockerfile
  ccm_web/package-lock.json
  ccm_web/package.json
  ccm_web/server/src/app.module.ts
  ccm_web/server/src/logger.ts
  ccm_web/server/src/lti/lti.module.ts
  ccm_web/server/src/lti/lti.service.ts
  ccm_web/server/src/migrations/2021.05.20T18.16.39.create-user.ts
  ccm_web/server/src/migrator.ts
  ccm_web/server/src/user/user.interfaces.ts
  ccm_web/server/src/user/user.model.ts
  ccm_web/server/src/user/user.module.ts
  ccm_web/server/src/user/user.service.ts
  config/lti_dev_key_sample.json
Labels: back end, enhancement
