Repository tl-its-umich-edu/canvas-course-manager-next, pull requests merged in 2021-06, with the labels that each got.

#84 Bulk section create
  ccm_web/.eslintrc.js
  ccm_web/client/src/api.ts
  ccm_web/client/src/components/BulkSectionCreateFileExample.tsx
  ccm_web/client/src/components/BulkSectionCreateUploadConfirmationTable.tsx
  ccm_web/client/src/components/BulkSectionCreateValidators.ts
  ccm_web/client/src/components/ConfirmationTable.tsx
  ccm_web/client/src/components/ConsumerTest.tsx
  ccm_web/client/src/components/GradebookCanvasValidators.ts
  ccm_web/client/src/components/GradebookUploadConfirmationTable.tsx
  ccm_web/client/src/components/StyledTableCell.tsx
  ccm_web/client/src/components/ValidationErrorTable.tsx
  ccm_web/client/src/models/FeatureUIData.tsx
  ccm_web/client/src/pages/BulkSectionCreate.tsx
  ccm_web/client/src/pages/GradebookCanvas.tsx
Labels: enhancement, front end

#94 Add `user` tableName to decorator (#93)
  ccm_web/server/src/user/user.model.ts
Labels: back end, bug

#92 Create foundation of Canvas integration with OAuth flow (#22, #95)
  README.md
  ccm_web/package-lock.json
  ccm_web/package.json
  ccm_web/server/localTypes/express-session/index.d.ts
  ccm_web/server/localTypes/ltijs/index.d.ts
  ccm_web/server/src/app.module.ts
  ccm_web/server/src/canvas/canvas.controller.ts
  ccm_web/server/src/canvas/canvas.interfaces.ts
  ccm_web/server/src/canvas/canvas.model.ts
  ccm_web/server/src/canvas/canvas.module.ts
  ccm_web/server/src/canvas/canvas.scopes.ts
  ccm_web/server/src/canvas/canvas.service.ts
  ccm_web/server/src/config.ts
  ccm_web/server/src/lti/lti.service.ts
  ccm_web/server/src/main.ts
  ccm_web/server/src/migrations/2021.06.08T13.39.45.create-canvas-token.ts
  ccm_web/server/src/user/user.model.ts
  ccm_web/server/src/user/user.module.ts
  ccm_web/server/src/user/user.service.ts
  config/.env.sample
Labels: back end, config change, enhancement

#116 Fix `returnFromOAuth` URL in README, provide recommended `CANVAS_INSTANCE_URL`
  README.md
  config/.env.sample
Labels: bug, documentation

#114 #106 Have some basic launch data available to UI
  ccm_web/client/src/models/models.ts
  ccm_web/server/localTypes/express-session/index.d.ts
  ccm_web/server/src/api/api.controller.ts
  ccm_web/server/src/api/api.interfaces.ts
  ccm_web/server/src/api/api.service.ts
  ccm_web/server/src/lti/lti.service.ts
  config/lti_dev_key_sample.json
Labels: API, back end, enhancement

#119 documentation and config sample update (iss. #118)
  README.md
  config/.env.sample
  config/lti_dev_key_sample.json
Labels: bug

#125 #124 waiting on DB container before Web container
  README.md
  ccm_web/Dockerfile
  ccm_web/package.json
  ccm_web/start.sh
  docker-compose-prod.yml
Labels: docker

#121 Implement Canvas requestor pattern, course name backend API routes (#99)
  ccm_web/package-lock.json
  ccm_web/package.json
  ccm_web/server/localTypes/@kth/canvas-api/index.d.ts
  ccm_web/server/localTypes/express-session/index.d.ts
  ccm_web/server/src/api/api.controller.spec.ts
  ccm_web/server/src/api/api.controller.ts
  ccm_web/server/src/api/api.interfaces.ts
  ccm_web/server/src/api/api.module.ts
  ccm_web/server/src/api/api.service.ts
  ccm_web/server/src/api/dtos/api.course.name.dto.ts
  ccm_web/server/src/canvas/canvas.interfaces.ts
  ccm_web/server/src/canvas/canvas.module.ts
  ccm_web/server/src/canvas/canvas.scopes.ts
  ccm_web/server/src/canvas/canvas.service.ts
  ccm_web/server/src/main.ts
  ccm_web/server/src/typeUtils.ts
Labels: API, back end, enhancement

#133 120 UI feature role accessibility
  ccm_web/client/src/App.tsx
  ccm_web/client/src/hooks/useGlobals.ts
  ccm_web/client/src/models/FeatureUIData.tsx
  ccm_web/client/src/models/feature.ts
  ccm_web/client/src/models/models.ts
  ccm_web/client/src/pages/Home.tsx
Labels: enhancement, front end

#130 #129 error message when needed scopes not selected
  ccm_web/server/src/canvas/canvas.controller.ts
  ccm_web/server/src/canvas/canvas.interfaces.ts
Labels: back end, bug

#140 configure Sequelize to log at `debug` level (iss. #91)
  README.md
  ccm_web/server/src/app.module.ts
Labels: config change

#127 Switch to using underscored table and field names (#126)
  ccm_web/server/src/app.module.ts
  ccm_web/server/src/canvas/canvas.model.ts
  ccm_web/server/src/migrations/2021.06.16T19.36.19.create-user.ts
  ccm_web/server/src/migrations/2021.06.16T19.36.43.create-canvas-token.ts
  ccm_web/server/src/migrator.ts
Labels: back end, bug
