Repository tl-its-umich-edu/canvas-course-manager-next, pull requests merged in 2021-03, with the labels that each got.

#24 Add Docker-ized basic stack with Express, React, and TypeScript (#14)
  .dockerignore
  .gitignore
  .vscode/settings.json
  README.md
  ccm_web/.eslintrc.js
  ccm_web/Dockerfile
  ccm_web/client/public/favicon.ico
  ccm_web/client/public/index.html
  ccm_web/client/public/robots.txt
  ccm_web/client/src/App.css
  ccm_web/client/src/App.test.tsx
  ccm_web/client/src/App.tsx
  ccm_web/client/src/components/ConsumerTest.tsx
  ccm_web/client/src/index.css
  ccm_web/client/src/index.tsx
  ccm_web/client/src/setupTests.ts
  ccm_web/client/tsconfig.json
  ccm_web/nmon_config.json
  ccm_web/package-lock.json
  ccm_web/package.json
  ccm_web/server/app.ts
  ccm_web/tsconfig.json
  ccm_web/webpack/webpack.common.ts
  ccm_web/webpack/webpack.dev.ts
  ccm_web/webpack/webpack.prod.ts
  docker-compose.yml
Labels: back end, enhancement, front end

#35 First pass at integrating Material UI
  ccm_web/client/src/App.tsx
  ccm_web/client/src/components/FeatureCard.tsx
  ccm_web/client/src/pages/Home.tsx
  ccm_web/package-lock.json
  ccm_web/package.json
Labels: front end

#41 Reactrouter
  ccm_web/client/src/App.tsx
  ccm_web/client/src/components/FeatureCard.tsx
  ccm_web/client/src/pages/Home.tsx
  ccm_web/client/src/pages/MergeSections.tsx
  ccm_web/package-lock.json
  ccm_web/package.json
Labels: enhancement, front end
