Repository tl-its-umich-edu/canvas-course-manager-next, pull requests merged in 2021-04, with the labels that each got.

#47 Course Rename
  ccm_web/client/src/App.tsx
  ccm_web/client/src/components/InlineTextEdit.tsx
  ccm_web/client/src/pages/Home.tsx
  ccm_web/package-lock.json
  ccm_web/package.json
Labels: enhancement, front end

#57 Change database flavor from PostgreSQL to MySQL (#49)
  .gitignore
  ccm_web/package-lock.json
  ccm_web/package.json
  ccm_web/server/appHandler.ts
  ccm_web/server/config.ts
  config/.env.sample
  docker-compose-prod.yml
  docker-compose.yml
Labels: back end, enhancement

#56 #54 adding Vscode debugger
  .vscode/launch.json
  README.md
  ccm_web/nmon_config.json
  ccm_web/package.json
  docker-compose.yml
Labels: back end, enhancement

#59 Add server logging approach using `winston` (#38)
  ccm_web/package-lock.json
  ccm_web/package.json
  ccm_web/server/app.ts
  ccm_web/server/appHandler.ts
  ccm_web/server/config.ts
  ccm_web/server/logger.ts
  config/.env.sample
Labels: back end, config change, enhancement
