Repository tl-its-umich-edu/canvas-course-manager-next, pull requests merged in 2021-11, with the labels that each got.

#226 Making Database autogenerated Id mandatory in Type definition
  ccm_web/server/src/auth/auth.service.ts
  ccm_web/server/src/canvas/canvas.model.ts
  ccm_web/server/src/user/user.model.ts
Labels: 🐛 bug, back end

#223 Implement Format Third-Party Gradebook feature (#21, #229)
  ccm_web/client/src/api.ts
  ccm_web/client/src/components/Alert.tsx
  ccm_web/client/src/components/ConfirmDialog.tsx
  ccm_web/client/src/components/ErrorAlert.tsx
  ccm_web/client/src/components/ExampleFileDownloadHeader.tsx
  ccm_web/client/src/components/RowLevelErrorsContent.tsx
  ccm_web/client/src/components/SuccessCard.tsx
  ccm_web/client/src/components/ThirdPartyGradebookConfirmationTable.tsx
  ccm_web/client/src/components/WarningAlert.tsx
  ccm_web/client/src/models/FeatureUIData.tsx
  ccm_web/client/src/models/feature.ts
  ccm_web/client/src/models/models.ts
  ccm_web/client/src/pages/AddUMUsers.tsx
  ccm_web/client/src/pages/BulkSectionCreate.tsx
  ccm_web/client/src/pages/FormatThirdPartyGradebook.tsx
  ccm_web/client/src/pages/GradebookCanvas.tsx
  ccm_web/client/src/utils/FileParserWrapper.ts
  ccm_web/client/src/utils/ThirdPartyGradebookProcessor.tsx
  ccm_web/client/src/utils/fileUtils.ts
  ccm_web/server/src/api/api.controller.ts
  ccm_web/server/src/api/api.section.handler.ts
  ccm_web/server/src/api/api.service.ts
  ccm_web/server/src/canvas/canvas.interfaces.ts
  ccm_web/server/src/canvas/canvas.scopes.ts
Labels: enhancement, front end, back end

#234 Add help link to "Format Third-Party Gradebook", tweak gradebook tools' language (#228, #233)
  ccm_web/client/src/App.tsx
  ccm_web/client/src/models/FeatureUIData.tsx
  ccm_web/client/src/models/feature.ts
  ccm_web/client/src/pages/AddUMUsers.tsx
  ccm_web/client/src/pages/BulkSectionCreate.tsx
  ccm_web/client/src/pages/FormatThirdPartyGradebook.tsx
  ccm_web/client/src/pages/GradebookCanvas.tsx
  ccm_web/client/src/pages/MergeSections.tsx
Labels: enhancement, front end

#239 Add success step to `GradebookCanvas.tsx` (#231)
  ccm_web/client/src/pages/GradebookCanvas.tsx
Labels: enhancement, front end

#236 Update dependencies (#173, #235)
  ccm_web/.eslintrc.js
  ccm_web/Dockerfile
  ccm_web/Dockerfile.openshift
  ccm_web/client/src/App.tsx
  ccm_web/client/src/components/CustomTable.tsx
  ccm_web/client/src/components/RowLevelErrorsContent.tsx
  ccm_web/client/src/components/TablePagination.tsx
  ccm_web/client/src/components/ValidationErrorTable.tsx
  ccm_web/client/src/index.tsx
  ccm_web/client/src/pages/FormatThirdPartyGradebook.tsx
  ccm_web/client/src/pages/GradebookCanvas.tsx
  ccm_web/client/src/utils/FileParserWrapper.ts
  ccm_web/package-lock.json
  ccm_web/package.json
  ccm_web/server/localTypes/@kth/canvas-api/index.d.ts
  ccm_web/server/src/api/api.admin.handler.ts
  ccm_web/server/src/api/api.course.handler.ts
  ccm_web/server/src/api/api.section.handler.ts
  ccm_web/server/src/api/api.service.ts
  ccm_web/server/src/api/api.utils.ts
  ccm_web/server/src/app.module.ts
  ccm_web/server/src/auth/auth.module.ts
  ccm_web/server/src/auth/auth.service.ts
  ccm_web/server/src/auth/jwt.strategy.ts
  ccm_web/server/src/canvas/canvas.module.ts
  ccm_web/server/src/canvas/canvas.service.ts
  ccm_web/server/src/config.ts
  ccm_web/server/src/lti/lti.module.ts
  ccm_web/server/src/lti/lti.service.ts
  ccm_web/server/src/main.ts
  docker-compose-prod.yml
Labels: enhancement, front end, back end, 🐳 docker, dependencies

#241 Refactor `InlineTextEdit` and course name usage to improve usability/accessibility (#240)
  ccm_web/client/src/components/InlineTextEdit.tsx
  ccm_web/client/src/pages/Home.tsx
Labels: 🐛 bug, front end, accessibility, usability

#250 Add check whether `getSectionsError` is `undefined` in "Format Third-Party Gradebook" (#249)
  ccm_web/client/src/pages/FormatThirdPartyGradebook.tsx
Labels: 🐛 bug, front end

#248 handle large input for section creation (iss. #217)
  ccm_web/server/src/api/dtos/api.create.sections.dto.ts
  ccm_web/server/src/main.ts
Labels: 🐛 bug, back end
