Repository tl-its-umich-edu/canvas-course-manager-next, pull requests merged in 2022-03, with the labels that each got.

#361 #358 file name change when downloading csv
  ccm_web/client/src/pages/FormatThirdPartyGradebook.tsx
  ccm_web/client/src/pages/GradebookCanvas.tsx
  ccm_web/client/src/utils/fileUtils.ts
Labels: enhancement, front end, usability

#360 #357 adjust the role in error report as in csv
  ccm_web/client/src/api.ts
  ccm_web/client/src/components/MultipleSectionEnrollmentWorkflow.tsx
  ccm_web/client/src/components/SingleSectionEnrollmentWorkflow.tsx
  ccm_web/client/src/components/UserEnrollmentForm.tsx
  ccm_web/client/src/models/canvas.ts
  ccm_web/server/src/api/api.section.handler.ts
  ccm_web/server/src/api/api.service.ts
  ccm_web/server/src/api/dtos/api.section.enrollment.dto.ts
  ccm_web/server/src/api/dtos/api.section.users.dto.ts
  ccm_web/server/src/canvas/canvas.interfaces.ts
Labels: enhancement, front end, back end

#345 Add root route and database health checks using `@nestjs/terminus` (#343)
  ccm_web/package-lock.json
  ccm_web/package.json
  ccm_web/server/src/app.module.ts
  ccm_web/server/src/health/health.controller.ts
  ccm_web/server/src/health/health.module.ts
Labels: enhancement, back end, API, dependencies

#332 Handle LTI launch error due to browser cookie settings (#312)
  ccm_web/client/src/components/HelpContact.tsx
  ccm_web/client/src/index.tsx
  ccm_web/client/src/pages/AccessDenied.tsx
  ccm_web/client/src/pages/LaunchError.tsx
  ccm_web/server/src/lti/lti.service.ts
Labels: 🐛 bug, front end, back end

#363 Integrate existing UI with API endpoints for Add Non-UM Users (#254)
  ccm_web/client/src/api.ts
  ccm_web/client/src/components/APIErrorsTable.tsx
  ccm_web/client/src/components/BulkApiErrorContent.tsx
  ccm_web/client/src/components/CanvasAPIErrorsTable.tsx
  ccm_web/client/src/components/MultipleUserEnrollmentWorkflow.tsx
  ccm_web/client/src/components/UserEnrollmentForm.tsx
  ccm_web/client/src/models/externalUser.ts
  ccm_web/client/src/models/models.ts
  ccm_web/client/src/models/typeUtils.ts
  ccm_web/client/src/utils/handleErrors.ts
  ccm_web/server/src/api/api.controller.ts
  ccm_web/server/src/api/api.interfaces.ts
  ccm_web/server/src/api/api.service.ts
  ccm_web/server/src/api/dtos/api.external.users.dto.ts
Labels: enhancement, feature, front end, back end, API

#362 #359 Dependency update
  ccm_web/package-lock.json
  ccm_web/package.json
Labels: front end, back end, dependencies

#368 Extract core setup to provide basic fix to end-to-end test (#237)
  ccm_web/server/src/config.ts
  ccm_web/server/src/main.ts
  ccm_web/server/test/app.e2e-spec.ts
Labels: 🐛 bug, back end, testing

#370 I300 remove the session expiration check
  ccm_web/client/src/utils/handleErrors.ts
  ccm_web/server/src/auth/csrf.exception.filter.ts
  ccm_web/server/src/auth/session.guard.ts
Labels: 🐛 bug, back end

#369 Use more DTOs
  ccm_web/server/src/api/api.controller.ts
  ccm_web/server/src/api/dtos/api.get.sections.admin.dto.ts
  ccm_web/server/src/api/dtos/api.get.sections.instructor.dto.ts
  ccm_web/server/src/canvas/canvas.controller.ts
  ccm_web/server/src/canvas/canvas.interfaces.ts
  ccm_web/server/src/canvas/dtos/canvas.oauth.query.dto.ts
Labels: 🐛 bug, back end, API

#374 Use an imperative validation message with inputs when the field is blank (#372)
  ccm_web/client/src/components/UserEnrollmentForm.tsx
  ccm_web/client/src/pages/Home.tsx
  ccm_web/client/src/utils/validation.ts
Labels: enhancement, front end, usability
