Repository tl-its-umich-edu/canvas-course-manager-next, pull requests merged in 2022-02, with the labels that each got.

#319 Streamline tab order on Home page, add hover/ripple for feature cards (#318)
  ccm_web/client/src/components/FeatureCard.tsx
Labels: enhancement, front end, accessibility, usability

#317 Add `aria-live` to `TablePagination`, remove it from `AddNonUMUsers` container (#258)
  ccm_web/client/src/components/CustomTable.tsx
  ccm_web/client/src/pages/AddNonUMUsers.tsx
Labels: 🐛 bug, front end, accessibility

#316 Allow for client-side routing, set up `/access-denied` (#48, #209)
  ccm_web/client/src/App.tsx
  ccm_web/client/src/components/Breadcrumbs.tsx
  ccm_web/client/src/components/InlineErrorAlert.tsx
  ccm_web/client/src/index.tsx
  ccm_web/client/src/pages/AccessDenied.tsx
  ccm_web/client/src/pages/NotFound.tsx
  ccm_web/client/src/utils/redirect.ts
  ccm_web/package-lock.json
  ccm_web/package.json
  ccm_web/server/src/api/api.service.ts
  ccm_web/server/src/app.module.ts
  ccm_web/server/src/config.ts
  ccm_web/server/src/lti/lti.service.ts
  ccm_web/server/src/main.ts
  config/.env.sample
Labels: front end, back end, config change, dependencies

#329 #328 change the contrast color ratio tabbing accordion
  ccm_web/client/src/components/Accordion.tsx
Labels: 🐛 bug, front end, accessibility

#337 Add table captions (#257)
  ccm_web/client/src/components/BulkEnrollExternalUserConfirmationTable.tsx
  ccm_web/client/src/components/BulkEnrollUMUserConfirmationTable.tsx
  ccm_web/client/src/components/BulkEnrollUMUserToSectionsConfirmationTable.tsx
  ccm_web/client/src/components/BulkSectionCreateUploadConfirmationTable.tsx
  ccm_web/client/src/components/CanvasAPIErrorsTable.tsx
  ccm_web/client/src/components/CustomTable.tsx
  ccm_web/client/src/components/GradebookUploadConfirmationTable.tsx
  ccm_web/client/src/components/MultipleSectionEnrollmentWorkflow.tsx
  ccm_web/client/src/components/TableCaption.tsx
  ccm_web/client/src/components/ThirdPartyGradebookConfirmationTable.tsx
  ccm_web/client/src/components/ValidationErrorTable.tsx
Labels: 🐛 bug, front end, accessibility

#334 Change list structure and otherwise improve `SectionSelectorWidget` (#230, #260)
  ccm_web/client/src/components/SectionSelectorWidget.tsx
  ccm_web/client/src/pages/MergeSections.tsx
Labels: 🐛 bug, enhancement, front end, accessibility

#327 Introduce `createLimitedPromises` wrapper for `p-limit` (#326)
  ccm_web/client/src/components/MultipleSectionEnrollmentWorkflow.tsx
  ccm_web/client/src/components/MultipleUserEnrollmentWorkflow.tsx
  ccm_web/client/src/components/SingleSectionEnrollmentWorkflow.tsx
  ccm_web/package-lock.json
  ccm_web/package.json
  ccm_web/server/src/api/api.admin.handler.ts
  ccm_web/server/src/api/api.course.handler.ts
  ccm_web/server/src/api/api.section.handler.ts
  ccm_web/server/src/api/api.service.ts
  ccm_web/server/src/api/api.utils.ts
  ccm_web/server/src/canvas/canvas.service.ts
Labels: 🐛 bug, back end, API

#344 I328 accordion tab change
  ccm_web/client/src/components/Accordion.tsx
Labels: 🐛 bug, front end, accessibility, usability

#350 Add `tabIndex` to `TableRow` to allow keyboard accessibility of scrollable table (#349)
  ccm_web/client/src/components/MultipleSectionEnrollmentWorkflow.tsx
Labels: 🐛 bug, front end, accessibility

#348 Create `Layout` component capturing base styling, breadcrumbs, footer, and development tools (#347, #352, #353)
  ccm_web/client/src/App.tsx
  ccm_web/client/src/components/Breadcrumbs.tsx
  ccm_web/client/src/components/Layout.tsx
  ccm_web/client/src/components/UserEnrollmentForm.tsx
  ccm_web/client/src/pages/AccessDenied.tsx
  ccm_web/client/src/pages/AddNonUMUsers.tsx
  ccm_web/client/src/pages/AddUMUsers.tsx
  ccm_web/client/src/pages/BulkSectionCreate.tsx
  ccm_web/client/src/pages/FormatThirdPartyGradebook.tsx
  ccm_web/client/src/pages/GradebookCanvas.tsx
  ccm_web/client/src/pages/Home.tsx
  ccm_web/client/src/pages/MergeSections.tsx
  ccm_web/client/src/pages/NotFound.tsx
Labels: enhancement, front end

#247 enroll non-UMich users (iss. #221, #169, #252, #291)
  README.md
  ccm_web/package-lock.json
  ccm_web/package.json
  ccm_web/server/src/api/api.admin.handler.ts
  ccm_web/server/src/api/api.controller.ts
  ccm_web/server/src/api/api.interfaces.ts
  ccm_web/server/src/api/api.module.ts
  ccm_web/server/src/api/api.section.handler.ts
  ccm_web/server/src/api/api.service.ts
  ccm_web/server/src/api/api.utils.ts
  ccm_web/server/src/api/dtos/api.external.users.dto.ts
  ccm_web/server/src/canvas/canvas.interfaces.ts
  ccm_web/server/src/canvas/canvas.service.ts
  ccm_web/server/src/config.ts
  ccm_web/server/src/invitation/cirrus-invitation.interfaces.ts
  ccm_web/server/src/invitation/cirrus-invitation.module.ts
  ccm_web/server/src/invitation/cirrus-invitation.service.ts
  ccm_web/server/src/invitation/invitation.errors.ts
  config/.env.sample
Labels: enhancement, API, config change

#340 Report API errors consistently, with and without snackbar (#272)
  ccm_web/client/src/App.tsx
  ccm_web/client/src/components/APIErrorMessage.tsx
  ccm_web/client/src/components/CourseSectionList.tsx
  ccm_web/client/src/components/CreateSectionWidget.tsx
  ccm_web/client/src/components/MultipleSectionEnrollmentWorkflow.tsx
  ccm_web/client/src/components/MultipleUserEnrollmentWorkflow.tsx
  ccm_web/client/src/components/SectionSelectorWidget.tsx
  ccm_web/client/src/components/SingleSectionEnrollmentWorkflow.tsx
  ccm_web/client/src/components/UserEnrollmentForm.tsx
  ccm_web/client/src/models/models.ts
  ccm_web/client/src/pages/BulkSectionCreate.tsx
  ccm_web/client/src/pages/FormatThirdPartyGradebook.tsx
  ccm_web/client/src/pages/Home.tsx
  ccm_web/client/src/pages/MergeSections.tsx
  ccm_web/client/src/utils/handleErrors.ts
Labels: enhancement, front end, usability
