Repository tl-its-umich-edu/canvas-course-manager-next, pull requests merged in 2022-04, with the labels that each got.

#379 Handle too many matching course results (#378)
  ccm_web/client/src/utils/handleErrors.ts
  ccm_web/server/src/api/api.admin.handler.ts
  ccm_web/server/src/api/api.controller.ts
  ccm_web/server/src/api/api.errors.ts
  ccm_web/server/src/api/api.service.ts
  ccm_web/server/src/api/too.many.results.interceptor.ts
  ccm_web/server/src/auth/csrf.exception.filter.ts
  ccm_web/server/src/config.ts
  config/.env.sample
Labels: 🐛 bug, front end, back end, API, config change

#383 Make UI style and text modifications (#382)
  ccm_web/client/src/components/SectionSelectorWidget.tsx
  ccm_web/client/src/models/feature.ts
  ccm_web/client/src/pages/MergeSections.tsx
Labels: 🐛 bug, front end, usability

#381 I225 layout for the docmentation
  docs/_data/home.yml
  docs/_data/navigation.yml
  docs/_includes/footer.html
  docs/_includes/nav.html
  docs/_layouts/default.html
  docs/add-non-um-users.html
  docs/add-um-users.html
  docs/assets/css/custom.css
  docs/assets/css/main.css
  docs/assets/images/um-logo.png
  docs/assets/images/um_logo.png
  docs/create-sections.html
  docs/gradebook-canvas.html
  docs/gradebook-thirdparty.html
  docs/index.html
  docs/merge-sections.html
Labels: documentation, enhancement
