Repository tl-its-umich-edu/canvas-course-manager-next, pull requests merged in 2022-01, with the labels that each got.

#275 Use `encodeURIComponent` with CSV download data for better character handling (#271)
  ccm_web/client/src/pages/FormatThirdPartyGradebook.tsx
  ccm_web/client/src/pages/GradebookCanvas.tsx
Labels: 🐛 bug, front end

#286 Rewire `ConfirmDialog` button to prevent double-focusing (#256)
  ccm_web/client/src/components/ConfirmDialog.tsx
Labels: 🐛 bug, front end, accessibility

#287 #283 Upgrading to Umzug v3
  ccm_web/package-lock.json
  ccm_web/package.json
Labels: enhancement, back end, dependencies

#270 Implement UI for Add Non-UM Users feature (#246)
  ccm_web/client/src/components/BulkApiErrorContent.tsx
  ccm_web/client/src/components/BulkEnrollExternalUserConfirmationTable.tsx
  ccm_web/client/src/components/BulkEnrollUMUserConfirmationTable.tsx
  ccm_web/client/src/components/BulkSectionCreateValidators.ts
  ccm_web/client/src/components/CreateSectionWidget.tsx
  ccm_web/client/src/components/CreateSelectSectionWidget.tsx
  ccm_web/client/src/components/GradebookCanvasValidators.ts
  ccm_web/client/src/components/InlineErrorAlert.tsx
  ccm_web/client/src/components/MethodSelect.tsx
  ccm_web/client/src/components/MultipleUserEnrollmentWorkflow.tsx
  ccm_web/client/src/components/RoleSelect.tsx
  ccm_web/client/src/components/UserEnrollmentForm.tsx
  ccm_web/client/src/components/ValidatedFormField.tsx
  ccm_web/client/src/components/WorkflowStepper.tsx
  ccm_web/client/src/models/FeatureUIData.tsx
  ccm_web/client/src/models/canvas.ts
  ccm_web/client/src/models/enrollment.ts
  ccm_web/client/src/models/models.ts
  ccm_web/client/src/pages/AddNonUMUsers.tsx
  ccm_web/client/src/pages/AddUMUsers.tsx
  ccm_web/client/src/pages/BulkSectionCreate.tsx
  ccm_web/client/src/pages/FormatThirdPartyGradebook.tsx
  ccm_web/client/src/utils/canvasSectionNameValidator.ts
  ccm_web/client/src/utils/enrollmentValidators.ts
  ccm_web/client/src/utils/fileUtils.ts
  ccm_web/client/src/utils/rowValidation.ts
  ccm_web/client/src/utils/validation.ts
Labels: enhancement, feature, front end

#294 Modify `CustomTable` so table semantics are used by screenreaders (#259)
  ccm_web/client/src/components/CustomTable.tsx
Labels: 🐛 bug, front end, accessibility

#298 Conditionally enable/disable section creation in `CreateSelectSectionWidget` (#284, #299)
  ccm_web/client/src/components/CreateSelectSectionWidget.tsx
  ccm_web/client/src/components/MultipleUserEnrollmentWorkflow.tsx
  ccm_web/client/src/models/FeatureUIData.tsx
  ccm_web/client/src/models/feature.ts
  ccm_web/client/src/pages/AddNonUMUsers.tsx
  ccm_web/client/src/pages/AddUMUsers.tsx
  ccm_web/client/src/pages/Home.tsx
  ccm_web/client/src/pages/MergeSections.tsx
Labels: 🐛 bug, front end

#303 Remove `colSpan` from `TablePagination` usages (#302)
  ccm_web/client/src/components/CustomTable.tsx
  ccm_web/client/src/components/ValidationErrorTable.tsx
Labels: 🐛 bug, front end

#306 Only intercept token-related `401` errors (#305)
  ccm_web/server/src/api/api.controller.ts
  ccm_web/server/src/api/invalid.token.interceptor.ts
Labels: 🐛 bug, back end, API

#288 Add "Back" and "Start Again" buttons where relevant (#238)
  ccm_web/client/src/components/ErrorAlert.tsx
  ccm_web/client/src/components/MethodSelect.tsx
  ccm_web/client/src/components/MultipleUserEnrollmentWorkflow.tsx
  ccm_web/client/src/components/UserEnrollmentForm.tsx
  ccm_web/client/src/models/FeatureUIData.tsx
  ccm_web/client/src/pages/AddNonUMUsers.tsx
  ccm_web/client/src/pages/AddUMUsers.tsx
  ccm_web/client/src/pages/BulkSectionCreate.tsx
  ccm_web/client/src/pages/FormatThirdPartyGradebook.tsx
  ccm_web/client/src/pages/GradebookCanvas.tsx
  ccm_web/client/src/pages/MergeSections.tsx
Labels: enhancement, front end, usability

#308 Disable `cors` in `LTIService` (#307)
  ccm_web/server/src/lti/lti.service.ts
Labels: enhancement, back end

#301 Enroll users to multiple sections with one CSV (#278)
  ccm_web/client/src/api.ts
  ccm_web/client/src/components/Accordion.tsx
  ccm_web/client/src/components/BulkEnrollExternalUserConfirmationTable.tsx
  ccm_web/client/src/components/BulkEnrollUMUserConfirmationTable.tsx
  ccm_web/client/src/components/BulkEnrollUMUserToSectionsConfirmationTable.tsx
  ccm_web/client/src/components/ExampleFileDownloadHeader.tsx
  ccm_web/client/src/components/MethodSelect.tsx
  ccm_web/client/src/components/MultipleSectionEnrollmentWorkflow.tsx
  ccm_web/client/src/components/MultipleUserEnrollmentWorkflow.tsx
  ccm_web/client/src/components/SingleSectionEnrollmentWorkflow.tsx
  ccm_web/client/src/components/StaticContentDownloadLink.tsx
  ccm_web/client/src/models/FeatureUIData.tsx
  ccm_web/client/src/models/enrollment.ts
  ccm_web/client/src/pages/AddNonUMUsers.tsx
  ccm_web/client/src/pages/AddUMUsers.tsx
  ccm_web/client/src/pages/FormatThirdPartyGradebook.tsx
  ccm_web/client/src/pages/GradebookCanvas.tsx
  ccm_web/client/src/utils/enrollmentValidators.ts
  ccm_web/client/src/utils/fileUtils.ts
  ccm_web/client/src/utils/validation.ts
  ccm_web/server/src/api/api.controller.ts
  ccm_web/server/src/api/api.service.ts
  ccm_web/server/src/api/dtos/api.section.enrollment.dto.ts
Labels: enhancement, feature, front end, back end, API
